### ISSUE TITLE
undefined method `from_json' for Daru::DataFrame:Class Did you mean? from_sql from_csv to_json

### ISSUE THREAD

**Issue by Shekharrajak** [Shekharrajak/daru_examples_io_view_rails#2]
<img width="1280" alt="screen shot 2017-08-02 at 11 44 10 am" src="https://user-images.githubusercontent.com/5774448/28859988-33988b8e-7778-11e7-8821-be945e9fef91.png">

I have added daru and daru-io in gemfile : https://github.com/Shekharrajak/daru_examples_io_view_rails/blob/master/Gemfile#L9

**Comment by Shekharrajak** [comment]
@athityakumar do you know why it is happening ?

**Comment by athityakumar** [comment]
@Shekharrajak - I'm guessing it's because daru-io hasn't been required anywhere?

**Comment by Shekharrajak** [comment]
In rails app, gems are automatically require from the gemfile. (For example, Daru also hasn't required but it doesn't show error: uninitialised Daru). I am trying to fix it.

**Comment by Shekharrajak** [comment]
I am seeing `Please install the json gem version, with gem install json to use the Daru::IO::Importers::JSON module.` when I did `gem 'daru-io', :git => 'https://github.com/athityakumar/daru-io.git', require: 'daru/io/importers/json'` in gemfile.

**Comment by Shekharrajak** [comment]
Ok cool! Adding 

```
gem 'jsonpath'
gem 'json'
```
fixed it.

**Comment by athityakumar** [comment]
Continuing with issue #7 regarding this. Closing this issue.
