### ISSUE TITLE
cannot load such file -- data_tables

### ISSUE THREAD

**Issue by Shekharrajak** [Shekharrajak/daru_examples_io_view_rails#3]
<img width="1144" alt="screen shot 2017-08-02 at 11 29 38 pm" src="https://user-images.githubusercontent.com/5774448/28887390-a727ae42-77da-11e7-8909-ef3ae38cef23.png">

We fixed similar error with Highcharts and nyaplot by adding it as `add_runtime_dependency` in gemspec. But data_tables is added in gemfile fetching from github repo in daru-view. There must be a good way to write it as run time dependency in gemfile.

**Comment by Shekharrajak** [comment]
Similar to this https://github.com/Shekharrajak/daru_examples_io_view_rails/issues/1 , https://github.com/Shekharrajak/daru-view/pull/46 ,

**Comment by athityakumar** [comment]
Fixed, as per commit 07cc873a0830e81ad8d4ecddda40b1b9cc6eef9b. Closing this issue.
