### ISSUE TITLE
host the app on heroku

### ISSUE THREAD

**Issue by lokeshh** [Shekharrajak/daru_examples_io_view_rails#8]

**Comment by Shekharrajak** [comment]
We tried this here https://github.com/Shekharrajak/daru_examples_io_view_rails/pull/5  but it was not working.  We are working on it.

**Comment by lokeshh** [comment]
@Shekharrajak What's the error?

**Comment by athityakumar** [comment]
The `Puma caught this error: undefined method 'helper_method' for ActionController::API:Class (NoMethodError)` error is crashing the app. Here's the brief heroku log :

```
2017-08-13T07:18:33.667971+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/google_visualr-2.5.1/lib/google_visualr/app/helpers/view_helper.rb:7:in `block in <module:ViewHelper>': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
2017-08-13T07:18:33.667986+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/google_visualr-2.5.1/lib/google_visualr/app/railtie.rb:11:in `include'
2017-08-13T07:18:33.667987+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/google_visualr-2.5.1/lib/google_visualr/app/railtie.rb:11:in `block (2 levels) in <class:Railtie>'
2017-08-13T07:18:33.667988+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/lazy_load_hooks.rb:45:in `instance_eval'
2017-08-13T07:18:33.667988+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/lazy_load_hooks.rb:45:in `execute_hook'
```

**Comment by lokeshh** [comment]
@athityakumar I'm also getting this error when I run the app locally and visit root path.

**Comment by athityakumar** [comment]
@lokeshh - Yes, but it disappears on refreshing. google_visualr gem is causing this error, and @Shekharrajak had opened https://github.com/winston/google_visualr/issues/117 for the same.

**Comment by lokeshh** [comment]
@Shekharrajak It could be that `google_visualr` just doesn't support Rails 5 yet. Try it with Rails 4.

**Comment by v0dro** [comment]
Try submitting this issue on the rails issue tracker. Those guys should know about this too, and they're pretty helpful.

@AnkurGel @gnilrets @zverok @shaunakpp can you Rails people please shed some light on this?

**Comment by AnkurGel** [comment]
@v0dro @athityakumar - It seems issue is fixed already but they haven't released the version yet. Refer : https://github.com/winston/google_visualr/commit/5dd3ffbb470da1d66f34826089a8ce62deffefa6 
They had the discussion here - https://github.com/winston/google_visualr/issues/104
I would try adding : 
`gem 'google_visualr', github: 'winston/google_visualr'` and update the gem with the master's copy.

**Comment by Shekharrajak** [comment]
@AnkurGel Thanks a lot!  I used `gem 'google_visualr', git: 'https://github.com/winston/google_visualr.git'` in [daru-view ](https://github.com/Shekharrajak/daru-view/blob/master/Gemfile#L10) but not in this repo. I thought It will take gem from the github repo only, but it wasn't.

Deployed here : 
https://daru-examples-io-view-rails.herokuapp.com/

**Comment by athityakumar** [comment]
Thanks a lot for the help, @AnkurGel 😄

**Comment by shaunakpp** [comment]
@Shekharrajak using gems directly from Github is not recommended but sometimes necessary, just to be sure, don't forget to use `ref` option in your `Gemfile` to refer to a particular commit in the master branch. This will avoid any regressions that may occur when the master branch is updated.
~~~ruby
gem 'google_visualr', github: 'winston/google_visualr', ref: '17b97114a345baadd011e7b442b9a6c91a2b7ab5'
~~~


And do keep track of that gem for any future stable releases so that you may stop referencing the Github repository altogether 😀

**Comment by athityakumar** [comment]
The master branch is now deployed at https://daru-examples-io-view-rails.herokuapp.com. Thanks a lot for your insights, @AnkurGel & @shaunakpp. Closing this issue for now. 😄
